"""Bundled multi-language sample prompts.

These let the multi-language comparison work fully offline (no translation API
needed). When the user types their *own* prompt and provides a Claude API key,
translate.py translates it live instead of using these.

The prompts are intentionally **long and verbose (~200 words)** — padded with
politeness, hedging, and redundancy — so the optimisation coach (Pillar 4) has
real bloat to cut and can show a meaningful before/after token saving.

Each sample maps a language label -> the same prompt in that language.
"""

LANGUAGES = ["English", "Spanish", "French", "Hindi", "Arabic", "Chinese", "Japanese"]

SAMPLES: dict[str, dict[str, str]] = {
    "Summarize an article": {
        "English": (
            "Hello there, I would really like you to please kindly help me out "
            "with something that is actually quite important to me. I have an "
            "article below, and what I basically want you to do is to read "
            "through the entire article very carefully and thoroughly from start "
            "to finish, and then, in order to help me understand it better, I "
            "would like you to write a summary of it for me. Please make sure "
            "that the summary is concise and to the point, but at the same time "
            "please also make sure that you do not leave out any of the really "
            "important key points or main ideas that the author is trying to get "
            "across to the reader. I would like the summary to be in the form of "
            "three bullet points, if you don't mind, and please try to keep each "
            "bullet point fairly short and easy to read. Also, it would be great "
            "if you could just make sure that the language you use is simple and "
            "clear so that anyone can understand it. Thank you so much in advance "
            "for your help with this, I really do appreciate it very much."
        ),
        "Spanish": (
            "Hola, me gustaría mucho que por favor me ayudaras amablemente con "
            "algo que en realidad es bastante importante para mí. Tengo un "
            "artículo abajo, y lo que básicamente quiero que hagas es leer todo "
            "el artículo con mucho cuidado y atención de principio a fin, y "
            "luego, para ayudarme a entenderlo mejor, me gustaría que me "
            "escribieras un resumen del mismo. Por favor, asegúrate de que el "
            "resumen sea conciso y vaya al grano, pero al mismo tiempo asegúrate "
            "también de no dejar fuera ninguno de los puntos clave o ideas "
            "principales realmente importantes que el autor intenta transmitir al "
            "lector. Me gustaría que el resumen tuviera la forma de tres "
            "viñetas, si no te importa, y por favor intenta que cada viñeta sea "
            "bastante corta y fácil de leer. Además, sería genial si pudieras "
            "simplemente asegurarte de que el lenguaje que uses sea sencillo y "
            "claro para que cualquiera pueda entenderlo. Muchísimas gracias de "
            "antemano por tu ayuda con esto, de verdad lo aprecio muchísimo."
        ),
        "French": (
            "Bonjour, j'aimerais vraiment que vous m'aidiez s'il vous plaît "
            "gentiment avec quelque chose qui est en fait assez important pour "
            "moi. J'ai un article ci-dessous, et ce que je veux essentiellement "
            "que vous fassiez, c'est de lire tout l'article très attentivement et "
            "soigneusement du début à la fin, puis, afin de m'aider à mieux le "
            "comprendre, j'aimerais que vous m'en rédigiez un résumé. Veuillez "
            "vous assurer que le résumé soit concis et précis, mais en même temps "
            "veillez aussi à ne laisser de côté aucun des points clés ou des "
            "idées principales vraiment importants que l'auteur essaie de "
            "transmettre au lecteur. J'aimerais que le résumé prenne la forme de "
            "trois points, si cela ne vous dérange pas, et veuillez essayer de "
            "garder chaque point assez court et facile à lire. De plus, ce serait "
            "formidable si vous pouviez simplement vous assurer que le langage "
            "que vous utilisez soit simple et clair afin que tout le monde puisse "
            "le comprendre. Merci beaucoup d'avance pour votre aide, je "
            "l'apprécie vraiment énormément."
        ),
        "Hindi": (
            "नमस्ते, मैं वास्तव में चाहूंगा कि आप कृपया मेरी एक ऐसी चीज़ में मदद करें जो "
            "असल में मेरे लिए काफ़ी महत्वपूर्ण है। नीचे मेरे पास एक लेख है, और मैं मूल रूप "
            "से चाहता हूं कि आप पूरे लेख को शुरू से अंत तक बहुत ध्यान से और सावधानी से "
            "पढ़ें, और फिर, इसे बेहतर ढंग से समझने में मेरी मदद करने के लिए, मैं चाहूंगा कि "
            "आप मेरे लिए इसका एक सारांश लिखें। कृपया सुनिश्चित करें कि सारांश संक्षिप्त और "
            "सटीक हो, लेकिन साथ ही यह भी सुनिश्चित करें कि आप उन वास्तव में महत्वपूर्ण मुख्य "
            "बिंदुओं या विचारों को न छोड़ें जिन्हें लेखक पाठक तक पहुंचाने की कोशिश कर रहा है। "
            "मैं चाहूंगा कि सारांश तीन बिंदुओं के रूप में हो, यदि आपको कोई आपत्ति न हो, और "
            "कृपया प्रत्येक बिंदु को काफ़ी छोटा और पढ़ने में आसान रखने का प्रयास करें। साथ ही, "
            "यह बहुत अच्छा होगा यदि आप यह सुनिश्चित कर सकें कि आपके द्वारा उपयोग की जाने "
            "वाली भाषा सरल और स्पष्ट हो ताकि कोई भी इसे समझ सके। इसमें आपकी मदद के लिए "
            "पहले से ही आपका बहुत-बहुत धन्यवाद, मैं वास्तव में इसकी बहुत सराहना करता हूं।"
        ),
        "Arabic": (
            "مرحبًا، أودّ حقًا أن تساعدني من فضلك بلطف في أمرٍ هو في الواقع مهمٌّ جدًا "
            "بالنسبة لي. لديّ مقال في الأسفل، وما أريده منك أساسًا هو أن تقرأ المقال "
            "كاملًا بعناية فائقة من البداية إلى النهاية، ثم، لمساعدتي على فهمه بشكل أفضل، "
            "أودّ أن تكتب لي ملخصًا له. من فضلك تأكّد من أن الملخص موجزٌ ومباشر، ولكن في "
            "الوقت نفسه تأكّد أيضًا من ألّا تُغفل أيًّا من النقاط الرئيسية أو الأفكار المهمة "
            "حقًا التي يحاول الكاتب إيصالها إلى القارئ. أودّ أن يكون الملخص على شكل ثلاث "
            "نقاط، إذا لم يكن لديك مانع، ومن فضلك حاول أن تجعل كل نقطة قصيرة نسبيًا وسهلة "
            "القراءة. كما سيكون رائعًا لو تأكّدت من أن اللغة التي تستخدمها بسيطة وواضحة حتى "
            "يتمكّن أي شخص من فهمها. شكرًا جزيلًا لك مقدمًا على مساعدتك في هذا الأمر، أنا "
            "حقًا أقدّر ذلك كثيرًا."
        ),
        "Chinese": (
            "你好，我真的非常希望你能够帮我一个忙，这件事其实对我来说相当重要。下面有一篇文章，"
            "我基本上想让你做的就是从头到尾非常仔细认真地把整篇文章通读一遍，然后，为了帮助我"
            "更好地理解它，我希望你能为我写一份摘要。请务必确保这份摘要简明扼要、切中要点，但与"
            "此同时也请确保不要遗漏作者试图向读者传达的任何真正重要的关键点或主要观点。如果你"
            "不介意的话，我希望这份摘要采用三个要点的形式，并且请尽量让每个要点都相当简短、易于"
            "阅读。另外，如果你能够确保所使用的语言简单清晰，让任何人都能看懂，那就太好了。非常"
            "感谢你提前为我提供帮助，我真的非常感激。"
        ),
        "Japanese": (
            "こんにちは。実は私にとってかなり重要なことについて、ぜひ手伝っていただけるととても助かります。"
            "下に記事がありますが、基本的にお願いしたいのは、その記事全体を最初から最後まで非常に注意深く"
            "丁寧に読んでいただき、そのうえで、私がより理解しやすいように、その要約を書いていただきたいという"
            "ことです。要約は簡潔で要点を押さえたものにしてください。ただし同時に、著者が読者に伝えようと"
            "している本当に重要な要点や主要な考えを一つも省かないようにもお願いします。もしよろしければ、"
            "要約は三つの箇条書きの形にしていただき、それぞれの項目はなるべく短く読みやすくしてください。"
            "また、誰でも理解できるように、使う言葉をできるだけ簡単で分かりやすいものにしていただけると大変"
            "ありがたいです。お手伝いいただけること、前もって心より感謝申し上げます。"
        ),
    },
    "Customer support reply": {
        "English": (
            "Hi, I was just wondering if you could please help me write a reply "
            "to one of our customers. So basically, we have this customer who is "
            "really quite unhappy and actually pretty upset right now, because "
            "unfortunately their order was delivered much later than it was "
            "originally supposed to be, and as a result of this late delivery, "
            "they are now asking us if we can please give them a full refund for "
            "their purchase. What I would like you to do is to write a polite, "
            "professional, and very friendly reply to this customer. Please make "
            "sure that in the reply you sincerely apologize to them for the delay "
            "and for any inconvenience that this may have caused them. Also, "
            "please make sure to let them know that we really do value them as a "
            "customer and that we genuinely care about their experience. In "
            "addition, please explain to them clearly what the next steps are "
            "going to be regarding their refund request. Try to keep the overall "
            "tone warm and understanding throughout the whole message. Thank you "
            "so much for helping me out with this task, I really appreciate it."
        ),
        "Spanish": (
            "Hola, solo me preguntaba si podrías ayudarme por favor a escribir "
            "una respuesta para uno de nuestros clientes. Básicamente, tenemos a "
            "este cliente que está realmente bastante descontento y de hecho "
            "bastante molesto en este momento, porque lamentablemente su pedido "
            "fue entregado mucho más tarde de lo que estaba previsto "
            "originalmente, y como resultado de esta entrega tardía, ahora nos "
            "está pidiendo si podemos por favor darle un reembolso completo de su "
            "compra. Lo que me gustaría que hicieras es escribir una respuesta "
            "cortés, profesional y muy amable para este cliente. Por favor, "
            "asegúrate de que en la respuesta te disculpes sinceramente con él "
            "por el retraso y por cualquier inconveniente que esto le haya podido "
            "causar. Además, por favor asegúrate de hacerle saber que de verdad "
            "lo valoramos como cliente y que realmente nos importa su "
            "experiencia. Asimismo, por favor explícale claramente cuáles van a "
            "ser los próximos pasos respecto a su solicitud de reembolso. Intenta "
            "mantener un tono cálido y comprensivo a lo largo de todo el mensaje. "
            "Muchas gracias por ayudarme con esta tarea, de verdad lo aprecio."
        ),
        "French": (
            "Bonjour, je me demandais simplement si vous pourriez s'il vous plaît "
            "m'aider à rédiger une réponse à l'un de nos clients. En gros, nous "
            "avons ce client qui est vraiment assez mécontent et en fait plutôt "
            "contrarié en ce moment, car malheureusement sa commande a été livrée "
            "bien plus tard que ce qui était initialement prévu, et à la suite de "
            "cette livraison tardive, il nous demande maintenant si nous pouvons "
            "s'il vous plaît lui accorder un remboursement complet de son achat. "
            "Ce que j'aimerais que vous fassiez, c'est rédiger une réponse polie, "
            "professionnelle et très aimable à ce client. Veuillez vous assurer "
            "que, dans la réponse, vous lui présentez sincèrement vos excuses "
            "pour le retard et pour tout désagrément que cela aurait pu lui "
            "causer. De plus, veuillez lui faire savoir que nous le considérons "
            "vraiment comme un client précieux et que son expérience nous tient "
            "réellement à cœur. En outre, veuillez lui expliquer clairement "
            "quelles seront les prochaines étapes concernant sa demande de "
            "remboursement. Essayez de garder un ton chaleureux et compréhensif "
            "tout au long du message. Merci beaucoup de m'aider, je l'apprécie "
            "vraiment."
        ),
        "Hindi": (
            "नमस्ते, मैं बस यह जानना चाहता था कि क्या आप कृपया हमारे एक ग्राहक के लिए एक "
            "उत्तर लिखने में मेरी मदद कर सकते हैं। मूल रूप से, हमारे पास एक ऐसा ग्राहक है जो "
            "इस समय वास्तव में काफ़ी असंतुष्ट और सच में काफ़ी नाराज़ है, क्योंकि दुर्भाग्य से "
            "उसका ऑर्डर मूल रूप से तय समय से बहुत देर से पहुंचाया गया, और इस देरी से हुई "
            "डिलीवरी के परिणामस्वरूप, वह अब हमसे पूछ रहा है कि क्या हम कृपया उसे उसकी खरीद "
            "का पूरा रिफंड दे सकते हैं। मैं चाहता हूं कि आप इस ग्राहक के लिए एक विनम्र, पेशेवर "
            "और बहुत मित्रवत उत्तर लिखें। कृपया सुनिश्चित करें कि उत्तर में आप उससे देरी और "
            "इससे हुई किसी भी असुविधा के लिए ईमानदारी से माफ़ी मांगें। साथ ही, कृपया उसे यह "
            "बताना सुनिश्चित करें कि हम वास्तव में एक ग्राहक के रूप में उसकी कद्र करते हैं और "
            "हमें सच में उसके अनुभव की परवाह है। इसके अलावा, कृपया उसे स्पष्ट रूप से समझाएं कि "
            "उसके रिफंड अनुरोध के संबंध में अगले कदम क्या होंगे। पूरे संदेश में एक गर्मजोशी भरा "
            "और समझदारी भरा लहजा बनाए रखने का प्रयास करें। इस काम में मेरी मदद करने के लिए "
            "बहुत-बहुत धन्यवाद, मैं वास्तव में इसकी सराहना करता हूं।"
        ),
        "Arabic": (
            "مرحبًا، كنت أتساءل فقط عمّا إذا كان بإمكانك من فضلك مساعدتي في كتابة ردٍّ "
            "لأحد عملائنا. في الأساس، لدينا هذا العميل الذي يشعر حقًا بعدم الرضا "
            "وبالانزعاج الشديد في الوقت الحالي، لأنه للأسف تمّ توصيل طلبه في وقت متأخر "
            "جدًا عمّا كان مقررًا في الأصل، ونتيجة لهذا التأخير في التسليم، أصبح الآن يطلب "
            "منّا ما إذا كان بإمكاننا أن نمنحه استردادًا كاملًا لقيمة مشترياته. ما أودّ منك "
            "أن تفعله هو كتابة ردٍّ مهذّب ومهني وودود جدًا لهذا العميل. من فضلك تأكّد من أن "
            "تعتذر له بصدق في الرد عن التأخير وعن أي إزعاج قد يكون قد سبّبه له ذلك. كما "
            "أرجو أن تحرص على إخباره بأننا نقدّره حقًا كعميل وأننا نهتمّ فعلًا بتجربته. "
            "بالإضافة إلى ذلك، يرجى أن توضّح له بشكل واضح ما هي الخطوات التالية فيما يتعلق "
            "بطلب الاسترداد الخاص به. حاول أن تحافظ على نبرة دافئة ومتفهّمة طوال الرسالة "
            "بأكملها. شكرًا جزيلًا لمساعدتي في هذه المهمة، أنا حقًا أقدّر ذلك."
        ),
        "Chinese": (
            "你好，我只是想问一下你是否能帮我给我们的一位客户写一封回复。基本上，我们有这样一位"
            "客户，他现在真的相当不满意，实际上也相当生气，因为很遗憾，他的订单比原定时间晚了很多"
            "才送达，而由于这次延迟送达，他现在正在询问我们是否可以给他的这笔购买办理全额退款。我"
            "希望你做的是为这位客户写一封礼貌、专业而且非常友好的回复。请务必在回复中真诚地为延误"
            "以及由此可能给他带来的任何不便向他道歉。此外，也请务必让他知道，我们真的非常重视他这"
            "位客户，并且真心在意他的体验。除此之外，还请清楚地向他说明关于他退款请求接下来将会有"
            "哪些步骤。请在整封信息中始终保持一种温暖且善解人意的语气。非常感谢你帮我完成这项任务，"
            "我真的非常感激。"
        ),
        "Japanese": (
            "こんにちは。お客様の一人への返信を書くのを手伝っていただけないかと思っています。基本的な"
            "状況としては、あるお客様が今、本当にかなりご不満で、実際かなりお怒りになっています。という"
            "のも、残念ながらそのお客様のご注文が当初の予定よりもずっと遅れて届いてしまい、その配達の"
            "遅れの結果として、購入代金の全額返金をしてもらえないかと現在お問い合わせをいただいている"
            "のです。お願いしたいのは、このお客様に対して、丁寧で、プロフェッショナルで、とても親しみ"
            "やすい返信を書いていただくことです。返信の中では、遅延とそれによってお客様におかけしたかも"
            "しれないご不便について、心からお詫びするようにしてください。また、私たちがお客様を本当に"
            "大切に思っており、お客様のご体験を心から気にかけていることを必ずお伝えください。さらに、"
            "返金のご依頼に関して今後どのような手順になるのかを、分かりやすくご説明ください。メッセージ"
            "全体を通して、温かく思いやりのある口調を保つようにしてください。この作業を手伝っていただき、"
            "本当にありがとうございます。心より感謝いたします。"
        ),
    },
    "Explain a concept": {
        "English": (
            "Hello, I hope you are doing well today. I have a question that I "
            "have been thinking about for quite a while now, and I would really "
            "appreciate it if you could help me out with it. Basically, I am "
            "trying to understand how a neural network actually learns, but the "
            "thing is, I am a complete beginner when it comes to this whole "
            "topic, so I do not really have any background knowledge in machine "
            "learning or artificial intelligence at all. So what I would like you "
            "to do is to please explain to me, in very simple and "
            "easy-to-understand terms, exactly how a neural network manages to "
            "learn from data over time. Please try to avoid using too much "
            "complicated technical jargon or overly mathematical language, "
            "because honestly that kind of thing just tends to confuse me quite a "
            "lot. If you could maybe use a simple analogy or a real-world example "
            "to help illustrate the idea, that would be absolutely wonderful and "
            "very helpful for me. Thank you so very much in advance, I really do "
            "appreciate you taking the time to explain this to me."
        ),
        "Spanish": (
            "Hola, espero que estés teniendo un buen día. Tengo una pregunta en "
            "la que llevo pensando bastante tiempo, y de verdad agradecería mucho "
            "que pudieras ayudarme con ella. Básicamente, estoy intentando "
            "entender cómo aprende realmente una red neuronal, pero el problema "
            "es que soy un completo principiante en todo este tema, así que en "
            "realidad no tengo ningún conocimiento previo de aprendizaje "
            "automático ni de inteligencia artificial. Así que lo que me gustaría "
            "que hicieras es explicarme, por favor, en términos muy sencillos y "
            "fáciles de entender, exactamente cómo logra una red neuronal "
            "aprender de los datos con el tiempo. Por favor, intenta evitar el "
            "uso de demasiada jerga técnica complicada o de un lenguaje "
            "excesivamente matemático, porque sinceramente ese tipo de cosas "
            "suele confundirme bastante. Si pudieras quizás usar una analogía "
            "sencilla o un ejemplo del mundo real para ayudar a ilustrar la idea, "
            "eso sería absolutamente maravilloso y muy útil para mí. Muchísimas "
            "gracias de antemano, de verdad aprecio que te tomes el tiempo de "
            "explicarme esto."
        ),
        "French": (
            "Bonjour, j'espère que vous allez bien aujourd'hui. J'ai une question "
            "à laquelle je réfléchis depuis un bon moment, et j'apprécierais "
            "vraiment beaucoup que vous puissiez m'aider à ce sujet. En gros, "
            "j'essaie de comprendre comment un réseau de neurones apprend "
            "réellement, mais le problème, c'est que je suis un parfait débutant "
            "en ce qui concerne tout ce sujet, donc je n'ai en réalité aucune "
            "connaissance préalable en apprentissage automatique ni en "
            "intelligence artificielle. Donc, ce que j'aimerais que vous fassiez, "
            "c'est de m'expliquer s'il vous plaît, en termes très simples et "
            "faciles à comprendre, exactement comment un réseau de neurones "
            "parvient à apprendre à partir des données au fil du temps. Veuillez "
            "essayer d'éviter d'utiliser trop de jargon technique compliqué ou un "
            "langage trop mathématique, car honnêtement ce genre de choses a "
            "tendance à beaucoup me perdre. Si vous pouviez éventuellement "
            "utiliser une analogie simple ou un exemple concret pour illustrer "
            "l'idée, ce serait absolument merveilleux et très utile pour moi. "
            "Merci infiniment d'avance, j'apprécie vraiment que vous preniez le "
            "temps de m'expliquer cela."
        ),
        "Hindi": (
            "नमस्ते, मुझे आशा है कि आपका दिन अच्छा बीत रहा होगा। मेरे मन में एक सवाल है "
            "जिसके बारे में मैं काफ़ी समय से सोच रहा हूं, और मैं सच में बहुत आभारी रहूंगा "
            "यदि आप इसमें मेरी मदद कर सकें। मूल रूप से, मैं यह समझने की कोशिश कर रहा हूं कि "
            "एक न्यूरल नेटवर्क असल में कैसे सीखता है, लेकिन बात यह है कि मैं इस पूरे विषय में "
            "बिल्कुल नौसिखिया हूं, इसलिए मेरे पास मशीन लर्निंग या आर्टिफिशियल इंटेलिजेंस का "
            "वास्तव में कोई पूर्व ज्ञान नहीं है। तो मैं चाहता हूं कि आप कृपया मुझे बहुत सरल और "
            "आसानी से समझ में आने वाले शब्दों में यह समझाएं कि एक न्यूरल नेटवर्क समय के साथ "
            "डेटा से सीखने में कैसे कामयाब होता है। कृपया बहुत अधिक जटिल तकनीकी शब्दावली या "
            "अत्यधिक गणितीय भाषा का उपयोग करने से बचने की कोशिश करें, क्योंकि सच कहूं तो इस "
            "तरह की चीज़ें मुझे काफ़ी हद तक भ्रमित कर देती हैं। यदि आप शायद इस विचार को समझाने "
            "में मदद के लिए कोई सरल उपमा या वास्तविक दुनिया का उदाहरण इस्तेमाल कर सकें, तो "
            "यह मेरे लिए बिल्कुल शानदार और बहुत मददगार होगा। पहले से ही आपका बहुत-बहुत "
            "धन्यवाद, मैं वास्तव में इसकी सराहना करता हूं कि आप मुझे यह समझाने के लिए समय "
            "निकाल रहे हैं।"
        ),
        "Arabic": (
            "مرحبًا، آمل أن يكون يومك جميلًا. لديّ سؤال ظللت أفكّر فيه منذ فترة طويلة، "
            "وسأكون ممتنًّا حقًا لو استطعت مساعدتي فيه. في الأساس، أحاول أن أفهم كيف "
            "تتعلّم الشبكة العصبية فعليًا، لكن المشكلة هي أنني مبتدئ تمامًا في هذا الموضوع "
            "بأكمله، لذا ليس لديّ في الواقع أي معرفة سابقة بتعلّم الآلة أو الذكاء الاصطناعي "
            "على الإطلاق. لذلك ما أودّ منك أن تفعله هو أن تشرح لي من فضلك، بعبارات بسيطة "
            "جدًا وسهلة الفهم، كيف تتمكّن الشبكة العصبية بالضبط من التعلّم من البيانات بمرور "
            "الوقت. أرجو أن تحاول تجنّب استخدام الكثير من المصطلحات التقنية المعقّدة أو "
            "اللغة الرياضية المفرطة، لأنني بصراحة أجد أن هذا النوع من الأمور يربكني كثيرًا. "
            "وإذا كان بإمكانك ربما استخدام تشبيه بسيط أو مثال من الواقع للمساعدة في توضيح "
            "الفكرة، فسيكون ذلك رائعًا للغاية ومفيدًا جدًا بالنسبة لي. شكرًا جزيلًا لك "
            "مقدمًا، أنا حقًا أقدّر أنك تخصّص من وقتك لشرح هذا لي."
        ),
        "Chinese": (
            "你好，希望你今天过得愉快。我有一个问题，已经思考了相当长的一段时间了，如果你能帮我"
            "解答，我会非常感激。基本上，我正在试图理解神经网络究竟是如何学习的，但问题是，我在这"
            "整个主题上完全是个新手，所以我其实根本没有任何机器学习或人工智能方面的背景知识。所以"
            "我希望你做的是，请用非常简单、易于理解的语言，向我准确地解释神经网络是如何随着时间从"
            "数据中学习的。请尽量避免使用太多复杂的技术术语或过于数学化的表达，因为说实话，那类东西"
            "往往会把我搞得相当糊涂。如果你能够使用一个简单的类比或一个现实生活中的例子来帮助说明"
            "这个概念，那对我来说就太棒了，也会非常有帮助。非常感谢你提前的帮助，我真的非常感激你"
            "抽出时间为我解释这个问题。"
        ),
        "Japanese": (
            "こんにちは。今日も良い一日をお過ごしのことと思います。実はかなり前からずっと考えている質問"
            "があり、もし手伝っていただけたら本当にありがたいです。基本的に、私はニューラルネットワークが"
            "実際にどのように学習するのかを理解しようとしているのですが、問題は、私がこの分野については"
            "全くの初心者で、機械学習や人工知能についての予備知識がまったくないということです。そこでお願い"
            "したいのは、ニューラルネットワークが時間をかけてどのようにデータから学習していくのかを、とても"
            "簡単で分かりやすい言葉で正確に説明していただくことです。あまり複雑な専門用語や過度に数学的な"
            "表現を使うのは避けていただけると助かります。正直なところ、そういったものはかなり私を混乱させて"
            "しまうからです。もし、その考え方を分かりやすく示すために簡単なたとえや現実世界の例を使って"
            "いただけたら、それは本当に素晴らしく、私にとってとても助かります。前もって本当にありがとう"
            "ございます。お時間を割いて説明してくださることに心より感謝します。"
        ),
    },
}
